# pytest.ini
[tool:pytest]
DJANGO_SETTINGS_MODULE = zestora.settings
python_files = tests.py test_*.py *_tests.py selenium_*.py
addopts = -v --tb=short --strict-markers --ds=zestora.settings
markers =
    selenium: marks tests as selenium tests (deselect with '-m "not selenium"')
    visual: marks tests as visual selenium tests (browser opens visibly)
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests