# Generated by Django 5.2.6 on 2025-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, help_text="Path to static image file (e.g., 'images/recipes/recipe-name.jpg')", max_length=255, null=True),
        ),
    ]
