# Generated by Django 5.2.6 on 2025-10-04 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipecomment_recipevariation_difficultyvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipecollection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipecollection',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='recipecollection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='recipereview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipereview',
            name='helpful_votes',
        ),
        migrations.RemoveField(
            model_name='recipereview',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipereview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipevariation',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='recipevariation',
            name='original_recipe',
        ),
        migrations.RemoveField(
            model_name='recipevariation',
            name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.comment')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DifficultyVote',
        ),
        migrations.DeleteModel(
            name='RecipeCollection',
        ),
        migrations.DeleteModel(
            name='RecipeComment',
        ),
        migrations.DeleteModel(
            name='RecipeReview',
        ),
        migrations.DeleteModel(
            name='RecipeVariation',
        ),
    ]
