# Generated by Django 5.2.6 on 2025-10-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipelike'),
    ]

    operations = [
    ]
